### ISSUE TITLE
[service] 初始化 读书历 api

### ISSUE THREAD

**Issue by zzswang** [zzswang/dushuli-api#6]
## 背景 

读书历是一款 微信 H5 小应用，每一天的日历对应一篇文章解读（语音）

只有付费用户能看

需求文档在此

https://axhub.im/pro/14d8ea1eade5f015

更多细节可以访问 slack 中的 `项目-读书历` 频道

api 服务需要同时支撑 H5 应用和中控台

## 需求

- 初始化 api 项目, 独立完成设计 api 以及数据库存储结构，与产品经理多沟通
- 基本实现 读书历的 api 需求，不包括 auth 服务，auth 服务有单独实现（邀请码也在 auth 中实现）
- api 目前我感觉只需要一个资源对应的CRUD，就是每天日历对应的内容
- 撰写 openapi.yml 文档
- 数据库用 mongodb
- test
- 根目录下放 postman.json

**Comment by lidongbest5** [comment]
reminder for adventure
